# Generated by Django 3.0.5 on 2020-05-09 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration', models.DurationField(help_text='Enter hours and minutes only')),
                ('url', models.CharField(blank=True, max_length=400)),
                ('price', models.DecimalField(decimal_places=3, max_digits=7)),
                ('cast', models.ManyToManyField(to='core.Cast')),
                ('tag', models.ManyToManyField(to='core.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
